import { App, Content, Path, PlatformType, json } from 'Dora';
import { EditorState } from 'Script/Tools/SceneEditor/EditorTypes';
import { pushConsole, workspacePath, workspaceRoot, zh } from 'Script/Tools/SceneEditor/Model';

declare function pcall(fn: () => unknown): LuaMultiReturn<[boolean, unknown]>;
declare const os: {
	execute?: (this: void, command: string) => unknown;
};

type ExportResult =
	| { success: true; root: string; initFile: string }
	| { success: false; message: string };

interface LaunchableApp {
	launch?: (appPath: string, launchArgs: string) => boolean;
}

function shellQuote(value: string) {
	let [escaped] = string.gsub(value, "'", "'\\''");
	return "'" + escaped + "'";
}

function luaLongString(value: string) {
	let level = 0;
	while (true) {
		let equals = '';
		for (let i = 0; i < level; i += 1) equals += '=';
		const close = ']' + equals + ']';
		const [found] = string.find(value, close, 1, true);
		if (found === undefined) return '[' + equals + '[' + value + close;
		level += 1;
	}
}

function appBundleFromAssetPath(assetPath: string) {
	const [startIndex, endIndex] = string.find(assetPath, '.app/Contents/Resources/Assets', 1, true);
	if (startIndex !== undefined && endIndex !== undefined) {
		return string.sub(assetPath, 1, startIndex + 3);
	}
	return undefined;
}

function findDoraAppBundle() {
	const fromAssetPath = appBundleFromAssetPath(Content.assetPath);
	if (fromAssetPath !== undefined && Content.exist(fromAssetPath)) return fromAssetPath;
	const candidates = [
		'/Users/wangyue/dora/build/Dora.app',
		'/Applications/Dora.app',
		'/Applications/Dora SSR.app',
		'/Applications/Dora/Dora.app',
	];
	for (const candidate of candidates) {
		if (Content.exist(candidate)) return candidate;
	}
	return undefined;
}

function sceneData(state: EditorState) {
	const nodes = [] as object[];
	for (const id of state.order) {
		const node = state.nodes[id];
		if (node !== undefined) {
			nodes.push({
				id: node.id,
				kind: node.kind,
				name: node.name,
				parentId: node.parentId,
				x: node.x,
				y: node.y,
				scaleX: node.scaleX,
				scaleY: node.scaleY,
				rotation: node.rotation,
				visible: node.visible,
				texture: node.texture,
				text: node.text,
				script: node.script,
			});
		}
	}
	return {
		version: 1,
		gameWidth: math.floor(math.max(160, state.gameWidth)),
		gameHeight: math.floor(math.max(120, state.gameHeight)),
		workspaceRoot: workspaceRoot(),
		nodes,
	};
}

function runtimeInitLua(workspace: string) {
	return `-- Generated by Dora Visual Editor external preview.
local _ENV = Dora

local workspaceRoot = ${luaLongString(workspace)}
Content:addSearchPath(workspaceRoot)
Content:addSearchPath(Path(workspaceRoot, "Imported"))
Content:addSearchPath(Path(workspaceRoot, "Script"))
Content:addSearchPath(Content.assetPath)
Content:clearPathCache()

local sceneFile = Path(Content.assetPath, "scene.json")
local sceneText = Content:load(sceneFile)
if not sceneText or sceneText == "" then
\terror("scene.json is missing")
end

local scene = json.decode(sceneText)
local gameWidth = math.max(160, tonumber(scene.gameWidth) or 960)
local gameHeight = math.max(120, tonumber(scene.gameHeight) or 540)
App.winSize = Size(gameWidth, gameHeight)

Director.entry:removeAllChildren(true)
local world = Node()
Director.entry:addChild(world)
local sceneRoot = Node()
world:addChild(sceneRoot)

local nodes = { root = sceneRoot }
local nodeDataById = {}

local function applyTransform(node, item)
\tnode.x = tonumber(item.x) or 0
\tnode.y = tonumber(item.y) or 0
\tnode.scaleX = tonumber(item.scaleX) or 1
\tnode.scaleY = tonumber(item.scaleY) or 1
\tnode.angle = tonumber(item.rotation) or 0
\tnode.visible = item.visible ~= false
\tnode.tag = tostring(item.name or "")
end

local function makeFallbackNode()
\treturn Node()
end

local function makeVisual(item)
\tif item.kind == "Sprite" then
\t\tlocal texture = tostring(item.texture or "")
\t\tif texture ~= "" then
\t\t\tlocal sprite = Sprite(texture)
\t\t\tif sprite then return sprite end
\t\tend
\t\treturn makeFallbackNode()
\telseif item.kind == "Label" then
\t\tlocal label = Label("sarasa-mono-sc-regular", 32)
\t\tif label then
\t\t\tlabel.text = tostring(item.text or "Label")
\t\t\treturn label
\t\tend
\t\treturn makeFallbackNode()
\tend
\treturn Node()
end

local activeCameraData = nil
for _, item in ipairs(scene.nodes or {}) do
\tnodeDataById[item.id] = item
\tif item.kind == "Camera" and item.visible ~= false and not activeCameraData then
\t\tactiveCameraData = item
\tend
end

for _, item in ipairs(scene.nodes or {}) do
\tif item.id ~= "root" then
\t\tlocal node = makeVisual(item)
\t\tapplyTransform(node, item)
\t\tnodes[item.id] = node
\t\tlocal parent = nodes[item.parentId or "root"] or sceneRoot
\t\tparent:addChild(node)
\tend
end

local activeCameraNode = activeCameraData and nodes[activeCameraData.id] or nil
local function updateCameraTransform()
\tif activeCameraNode then
\t\tworld.x = -(tonumber(activeCameraNode.x) or 0)
\t\tworld.y = -(tonumber(activeCameraNode.y) or 0)
\t\tworld.angle = -(tonumber(activeCameraNode.angle) or 0)
\t\tlocal sx = tonumber(activeCameraNode.scaleX) or 1
\t\tlocal sy = tonumber(activeCameraNode.scaleY) or 1
\t\tworld.scaleX = sx ~= 0 and 1 / sx or 1
\t\tworld.scaleY = sy ~= 0 and 1 / sy or 1
\telse
\t\tworld.x = 0
\t\tworld.y = 0
\t\tworld.angle = 0
\t\tworld.scaleX = 1
\t\tworld.scaleY = 1
\tend
end
updateCameraTransform()
world:schedule(function()
\tupdateCameraTransform()
\treturn false
end)

local function readScript(script)
\tif not script or script == "" then return "" end
\tlocal absolute = Path(workspaceRoot, script)
\tif Content:exist(absolute) then return Content:load(absolute) or "" end
\tif Content:exist(script) then return Content:load(script) or "" end
\treturn ""
end

for _, item in ipairs(scene.nodes or {}) do
\tlocal runtimeNode = nodes[item.id]
\tif runtimeNode and item.script and item.script ~= "" then
\t\tlocal scriptText = readScript(item.script)
\t\tif scriptText ~= "" then
\t\t\tlocal chunk, loadError = load(scriptText, item.script)
\t\t\tif chunk then
\t\t\t\tlocal ok, result = pcall(chunk)
\t\t\t\tif ok and type(result) == "function" then
\t\t\t\t\tlocal attachOk, attachError = pcall(function()
\t\t\t\t\t\tresult(runtimeNode, sceneRoot, nodes)
\t\t\t\t\tend)
\t\t\t\t\tif not attachOk then print("Script attach failed: " .. tostring(attachError)) end
\t\t\t\telseif not ok then
\t\t\t\t\tprint("Script failed: " .. tostring(result))
\t\t\t\tend
\t\t\telse
\t\t\t\tprint("Script load failed: " .. tostring(loadError))
\t\t\tend
\t\tend
\tend
end
`;
}

export function exportRunPreviewProject(state: EditorState): ExportResult {
	const root = workspacePath(Path('.dora', 'run-preview'));
	Content.mkdir(workspacePath('.dora'));
	Content.mkdir(root);
	const [sceneText] = json.encode(sceneData(state));
	if (sceneText === undefined || !Content.save(Path(root, 'scene.json'), sceneText)) {
		return { success: false, message: zh ? '写入运行场景失败' : 'Failed to write preview scene' };
	}
	const initFile = Path(root, 'init.lua');
	if (!Content.save(initFile, runtimeInitLua(workspaceRoot()))) {
		return { success: false, message: zh ? '写入运行入口失败' : 'Failed to write preview init.lua' };
	}
	return { success: true, root, initFile };
}

export function launchExternalPreview(state: EditorState) {
	const exported = exportRunPreviewProject(state);
	if (!exported.success) {
		state.status = exported.message;
		pushConsole(state, state.status);
		return false;
	}
	state.externalPreviewRoot = exported.root;
	if (App.platform !== PlatformType.macOS) {
		state.status = zh ? '当前只接入了 macOS 外部窗口启动' : 'External preview launch is wired for macOS only';
		pushConsole(state, state.status);
		return false;
	}
	const appBundle = findDoraAppBundle();
	if (appBundle === undefined) {
		state.status = zh ? '找不到 Dora.app，已生成预览项目：' + exported.root : 'Dora.app not found, preview project generated: ' + exported.root;
		pushConsole(state, state.status);
		return false;
	}
	const launchableApp = App as unknown as LaunchableApp;
	const launchArguments = '--asset ' + shellQuote(exported.root);
	if (launchableApp.launch !== undefined) {
		const [ok, result] = pcall(() => launchableApp.launch!(appBundle, launchArguments));
		if (!ok || result !== true) {
			state.status = (zh ? '启动外部预览失败：' : 'Failed to launch external preview: ') + tostring(ok ? result : result);
			pushConsole(state, state.status);
			return false;
		}
	} else if (os.execute !== undefined) {
		const command = 'open -n ' + shellQuote(appBundle) + ' --args ' + launchArguments;
		const [ok, err] = pcall(() => os.execute!(command));
		if (!ok) {
			state.status = (zh ? '启动外部预览失败：' : 'Failed to launch external preview: ') + tostring(err);
			pushConsole(state, state.status);
			return false;
		}
	} else {
		state.status = zh ? '当前引擎缺少 App.launch；请先使用新构建的 Dora.app。预览项目：' + exported.root : 'App.launch is unavailable; use the newly built Dora.app. Preview project: ' + exported.root;
		pushConsole(state, state.status);
		return false;
	}
	state.externalPreviewRunning = true;
	state.status = zh ? '已打开外部游戏窗口' : 'External game window opened';
	pushConsole(state, state.status);
	return true;
}

export function stopExternalPreview(state: EditorState) {
	state.externalPreviewRunning = false;
	state.status = zh ? '外部预览标记已停止；请关闭游戏窗口' : 'External preview marked stopped; close the game window manually';
	pushConsole(state, state.status);
}
