-- [ts]: ExternalPreview.ts
local ____exports = {} -- 1
local ____Dora = require("Dora") -- 1
local App = ____Dora.App -- 1
local Content = ____Dora.Content -- 1
local Path = ____Dora.Path -- 1
local json = ____Dora.json -- 1
local ____Model = require("Script.Tools.SceneEditor.Model") -- 3
local pushConsole = ____Model.pushConsole -- 3
local workspacePath = ____Model.workspacePath -- 3
local workspaceRoot = ____Model.workspaceRoot -- 3
local zh = ____Model.zh -- 3
local function shellQuote(value) -- 18
	local escaped = string.gsub(value, "'", "'\\''") -- 19
	return ("'" .. escaped) .. "'" -- 20
end -- 18
local function luaLongString(value) -- 23
	local level = 0 -- 24
	while true do -- 24
		local equals = "" -- 26
		do -- 26
			local i = 0 -- 27
			while i < level do -- 27
				equals = equals .. "=" -- 27
				i = i + 1 -- 27
			end -- 27
		end -- 27
		local close = ("]" .. equals) .. "]" -- 28
		local found = string.find(value, close, 1, true) -- 29
		if found == nil then -- 29
			return ((("[" .. equals) .. "[") .. value) .. close -- 30
		end -- 30
		level = level + 1 -- 31
	end -- 31
end -- 23
local function appBundleFromAssetPath(assetPath) -- 35
	local startIndex, endIndex = string.find(assetPath, ".app/Contents/Resources/Assets", 1, true) -- 36
	if startIndex ~= nil and endIndex ~= nil then -- 36
		return string.sub(assetPath, 1, startIndex + 3) -- 38
	end -- 38
	return nil -- 40
end -- 35
local function findDoraAppBundle() -- 43
	local fromAssetPath = appBundleFromAssetPath(Content.assetPath) -- 44
	if fromAssetPath ~= nil and Content:exist(fromAssetPath) then -- 44
		return fromAssetPath -- 45
	end -- 45
	local candidates = {"/Users/wangyue/dora/build/Dora.app", "/Applications/Dora.app", "/Applications/Dora SSR.app", "/Applications/Dora/Dora.app"} -- 46
	for ____, candidate in ipairs(candidates) do -- 52
		if Content:exist(candidate) then -- 52
			return candidate -- 53
		end -- 53
	end -- 53
	return nil -- 55
end -- 43
local function sceneData(state) -- 58
	local nodes = {} -- 59
	for ____, id in ipairs(state.order) do -- 60
		local node = state.nodes[id] -- 61
		if node ~= nil then -- 61
			nodes[#nodes + 1] = { -- 63
				id = node.id, -- 64
				kind = node.kind, -- 65
				name = node.name, -- 66
				parentId = node.parentId, -- 67
				x = node.x, -- 68
				y = node.y, -- 69
				scaleX = node.scaleX, -- 70
				scaleY = node.scaleY, -- 71
				rotation = node.rotation, -- 72
				visible = node.visible, -- 73
				texture = node.texture, -- 74
				text = node.text, -- 75
				script = node.script -- 76
			} -- 76
		end -- 76
	end -- 76
	return { -- 80
		version = 1, -- 81
		gameWidth = math.floor(math.max(160, state.gameWidth)), -- 82
		gameHeight = math.floor(math.max(120, state.gameHeight)), -- 83
		workspaceRoot = workspaceRoot(), -- 84
		nodes = nodes -- 85
	} -- 85
end -- 58
local function runtimeInitLua(workspace) -- 89
	return ("-- Generated by Dora Visual Editor external preview.\nlocal _ENV = Dora\n\nlocal workspaceRoot = " .. luaLongString(workspace)) .. "\nContent:addSearchPath(workspaceRoot)\nContent:addSearchPath(Path(workspaceRoot, \"Imported\"))\nContent:addSearchPath(Path(workspaceRoot, \"Script\"))\nContent:addSearchPath(Content.assetPath)\nContent:clearPathCache()\n\nlocal sceneFile = Path(Content.assetPath, \"scene.json\")\nlocal sceneText = Content:load(sceneFile)\nif not sceneText or sceneText == \"\" then\n\terror(\"scene.json is missing\")\nend\n\nlocal scene = json.decode(sceneText)\nlocal gameWidth = math.max(160, tonumber(scene.gameWidth) or 960)\nlocal gameHeight = math.max(120, tonumber(scene.gameHeight) or 540)\nApp.winSize = Size(gameWidth, gameHeight)\n\nDirector.entry:removeAllChildren(true)\nlocal world = Node()\nDirector.entry:addChild(world)\nlocal sceneRoot = Node()\nworld:addChild(sceneRoot)\n\nlocal nodes = { root = sceneRoot }\nlocal nodeDataById = {}\n\nlocal function applyTransform(node, item)\n\tnode.x = tonumber(item.x) or 0\n\tnode.y = tonumber(item.y) or 0\n\tnode.scaleX = tonumber(item.scaleX) or 1\n\tnode.scaleY = tonumber(item.scaleY) or 1\n\tnode.angle = tonumber(item.rotation) or 0\n\tnode.visible = item.visible ~= false\n\tnode.tag = tostring(item.name or \"\")\nend\n\nlocal function makeFallbackNode()\n\treturn Node()\nend\n\nlocal function makeVisual(item)\n\tif item.kind == \"Sprite\" then\n\t\tlocal texture = tostring(item.texture or \"\")\n\t\tif texture ~= \"\" then\n\t\t\tlocal sprite = Sprite(texture)\n\t\t\tif sprite then return sprite end\n\t\tend\n\t\treturn makeFallbackNode()\n\telseif item.kind == \"Label\" then\n\t\tlocal label = Label(\"sarasa-mono-sc-regular\", 32)\n\t\tif label then\n\t\t\tlabel.text = tostring(item.text or \"Label\")\n\t\t\treturn label\n\t\tend\n\t\treturn makeFallbackNode()\n\tend\n\treturn Node()\nend\n\nlocal activeCameraData = nil\nfor _, item in ipairs(scene.nodes or {}) do\n\tnodeDataById[item.id] = item\n\tif item.kind == \"Camera\" and item.visible ~= false and not activeCameraData then\n\t\tactiveCameraData = item\n\tend\nend\n\nfor _, item in ipairs(scene.nodes or {}) do\n\tif item.id ~= \"root\" then\n\t\tlocal node = makeVisual(item)\n\t\tapplyTransform(node, item)\n\t\tnodes[item.id] = node\n\t\tlocal parent = nodes[item.parentId or \"root\"] or sceneRoot\n\t\tparent:addChild(node)\n\tend\nend\n\nlocal activeCameraNode = activeCameraData and nodes[activeCameraData.id] or nil\nlocal function updateCameraTransform()\n\tif activeCameraNode then\n\t\tworld.x = -(tonumber(activeCameraNode.x) or 0)\n\t\tworld.y = -(tonumber(activeCameraNode.y) or 0)\n\t\tworld.angle = -(tonumber(activeCameraNode.angle) or 0)\n\t\tlocal sx = tonumber(activeCameraNode.scaleX) or 1\n\t\tlocal sy = tonumber(activeCameraNode.scaleY) or 1\n\t\tworld.scaleX = sx ~= 0 and 1 / sx or 1\n\t\tworld.scaleY = sy ~= 0 and 1 / sy or 1\n\telse\n\t\tworld.x = 0\n\t\tworld.y = 0\n\t\tworld.angle = 0\n\t\tworld.scaleX = 1\n\t\tworld.scaleY = 1\n\tend\nend\nupdateCameraTransform()\nworld:schedule(function()\n\tupdateCameraTransform()\n\treturn false\nend)\n\nlocal function readScript(script)\n\tif not script or script == \"\" then return \"\" end\n\tlocal absolute = Path(workspaceRoot, script)\n\tif Content:exist(absolute) then return Content:load(absolute) or \"\" end\n\tif Content:exist(script) then return Content:load(script) or \"\" end\n\treturn \"\"\nend\n\nfor _, item in ipairs(scene.nodes or {}) do\n\tlocal runtimeNode = nodes[item.id]\n\tif runtimeNode and item.script and item.script ~= \"\" then\n\t\tlocal scriptText = readScript(item.script)\n\t\tif scriptText ~= \"\" then\n\t\t\tlocal chunk, loadError = load(scriptText, item.script)\n\t\t\tif chunk then\n\t\t\t\tlocal ok, result = pcall(chunk)\n\t\t\t\tif ok and type(result) == \"function\" then\n\t\t\t\t\tlocal attachOk, attachError = pcall(function()\n\t\t\t\t\t\tresult(runtimeNode, sceneRoot, nodes)\n\t\t\t\t\tend)\n\t\t\t\t\tif not attachOk then print(\"Script attach failed: \" .. tostring(attachError)) end\n\t\t\t\telseif not ok then\n\t\t\t\t\tprint(\"Script failed: \" .. tostring(result))\n\t\t\t\tend\n\t\t\telse\n\t\t\t\tprint(\"Script load failed: \" .. tostring(loadError))\n\t\t\tend\n\t\tend\n\tend\nend\n"
end -- 89
function ____exports.exportRunPreviewProject(state) -- 210
	local root = workspacePath(Path(".dora", "run-preview")) -- 211
	Content:mkdir(workspacePath(".dora")) -- 212
	Content:mkdir(root) -- 213
	local sceneText = json.encode(sceneData(state)) -- 214
	if sceneText == nil or not Content:save( -- 214
		Path(root, "scene.json"), -- 215
		sceneText -- 215
	) then -- 215
		return {success = false, message = zh and "写入运行场景失败" or "Failed to write preview scene"} -- 216
	end -- 216
	local initFile = Path(root, "init.lua") -- 218
	if not Content:save( -- 218
		initFile, -- 219
		runtimeInitLua(workspaceRoot()) -- 219
	) then -- 219
		return {success = false, message = zh and "写入运行入口失败" or "Failed to write preview init.lua"} -- 220
	end -- 220
	return {success = true, root = root, initFile = initFile} -- 222
end -- 210
function ____exports.launchExternalPreview(state) -- 225
	local exported = ____exports.exportRunPreviewProject(state) -- 226
	if not exported.success then -- 226
		state.status = exported.message -- 228
		pushConsole(state, state.status) -- 229
		return false -- 230
	end -- 230
	state.externalPreviewRoot = exported.root -- 232
	if App.platform ~= "macOS" then -- 232
		state.status = zh and "当前只接入了 macOS 外部窗口启动" or "External preview launch is wired for macOS only" -- 234
		pushConsole(state, state.status) -- 235
		return false -- 236
	end -- 236
	local appBundle = findDoraAppBundle() -- 238
	if appBundle == nil then -- 238
		state.status = zh and "找不到 Dora.app，已生成预览项目：" .. exported.root or "Dora.app not found, preview project generated: " .. exported.root -- 240
		pushConsole(state, state.status) -- 241
		return false -- 242
	end -- 242
	local launchableApp = App -- 244
	local launchArguments = "--asset " .. shellQuote(exported.root)
	if launchableApp.launch ~= nil then -- 245
		local ok, result = pcall(function() return launchableApp:launch(appBundle, launchArguments) end) -- 247
		if not ok or result ~= true then -- 247
			local ____state_3 = state -- 249
			local ____temp_2 = zh and "启动外部预览失败：" or "Failed to launch external preview: " -- 249
			local ____tostring_1 = tostring -- 249
			local ____ok_0 -- 249
			if ok then -- 249
				____ok_0 = result -- 249
			else -- 249
				____ok_0 = result -- 249
			end -- 249
			____state_3.status = ____temp_2 .. ____tostring_1(____ok_0) -- 249
			pushConsole(state, state.status) -- 250
			return false -- 251
		end -- 251
	elseif os.execute ~= nil then -- 251
		local command = (("open -n " .. shellQuote(appBundle)) .. " --args ") .. launchArguments
		local ok, err = pcall(function() return os.execute(command) end) -- 255
		if not ok then -- 255
			state.status = (zh and "启动外部预览失败：" or "Failed to launch external preview: ") .. tostring(err) -- 257
			pushConsole(state, state.status) -- 258
			return false -- 259
		end -- 259
	else -- 259
		state.status = zh and "当前引擎缺少 App.launch；请先使用新构建的 Dora.app。预览项目：" .. exported.root or "App.launch is unavailable; use the newly built Dora.app. Preview project: " .. exported.root -- 262
		pushConsole(state, state.status) -- 263
		return false -- 264
	end -- 264
	state.externalPreviewRunning = true -- 266
	state.status = zh and "已打开外部游戏窗口" or "External game window opened" -- 267
	pushConsole(state, state.status) -- 268
	return true -- 269
end -- 225
function ____exports.stopExternalPreview(state) -- 272
	state.externalPreviewRunning = false -- 273
	state.status = zh and "外部预览标记已停止；请关闭游戏窗口" or "External preview marked stopped; close the game window manually" -- 274
	pushConsole(state, state.status) -- 275
end -- 272
return ____exports -- 272